const myanmarToEnglishInitial = {
    'က': 'K',
    'ခ': 'Kh',
    'ဂ': 'G',
    'ဃ': 'Gh',
    'င': 'N',
    'စ': 'S',
    'ဆ': 'Sh',
    'ဇ': 'Z',
    'ဈ': 'Zh',
    'ည': 'Ny',
    'ဋ': 'T',
    'ဌ': 'Th',
    'ဍ': 'D',
    'ဎ': 'Dh',
    'ဏ': 'N',
    'တ': 'T',
    'ထ': 'Ht',
    'ဒ': 'D',
    'ဓ': 'Dh',
    'န': 'N',
    'ပ': 'P',
    'ဖ': 'Ph',
    'ဗ': 'B',
    'ဘ': 'Bh',
    'မ': 'M',
    'ယ': 'Y',
    'ရ': 'R',
    'လ': 'L',
    'ဝ': 'W',
    'သ': 'Th',
    'ဟ': 'H',
    'ဠ': 'L',
    'အ': 'A'
  };

export default myanmarToEnglishInitial
  